### ISSUE TITLE
Buildpack not working

### ISSUE THREAD

**Issue by mhubig** [paketo-buildpacks/datadog#18]
I'm new to buildpacks and tried to inject the dd-agent into my java app build but it somehow failed. My app is a very simple spring-cloud java app build with gradle. Without the dadatog-buildpack it works like a charm. If you need some more Informations, don't hesitate to ask ...

```shell
pack build base-product-service --builder paketobuildpacks/builder:tiny --buildpack paketo-buildpacks/datadog@0.1.0 --buildpack paketo-buildpacks/java@6.9.0

base: Pulling from paketobuildpacks/builder
Digest: sha256:92b2e65a82eb5fef2f6acbb27468506802284bf49c14658f0bb861d995694823
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:bcab6379bf83f0657dab49f08c7da7f23a6b18145352b2e13178e35cf6bd39c1
Status: Image is up to date for paketobuildpacks/run:base-cnb
gcr.io/paketo-buildpacks/datadog@sha256:6f94305055e61bfb03d8c8a84679e8ef7c5971c060ee613ca1e653baf13b1a07: Pulling from paketo-buildpacks/datadog
Digest: sha256:6f94305055e61bfb03d8c8a84679e8ef7c5971c060ee613ca1e653baf13b1a07
Status: Image is up to date for gcr.io/paketo-buildpacks/datadog@sha256:6f94305055e61bfb03d8c8a84679e8ef7c5971c060ee613ca1e653baf13b1a07
gcr.io/paketo-buildpacks/java@sha256:190e0e0fca654c7991d770087acf0c9b8f551780f435bc0893217061be02ba70: Pulling from paketo-buildpacks/java
Digest: sha256:190e0e0fca654c7991d770087acf0c9b8f551780f435bc0893217061be02ba70
Status: Image is up to date for gcr.io/paketo-buildpacks/java@sha256:190e0e0fca654c7991d770087acf0c9b8f551780f435bc0893217061be02ba70
===> ANALYZING
Restoring data for sbom from previous image
===> DETECTING
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```

**Comment by dmikusa-pivotal** [comment]
In short, there are more steps to using this buildpack than just adding it to the list. I apologize that we don't have the steps documented yet, but this buildpack is still being actively developed (pre-1.0) and we're still working on that.

If you're interested in testing, I have these instructions which will likely be the base of our docs. Feedback is definitely appreciated!

1. Download pack cli -> https://github.com/buildpacks/pack/releases (you can also `brew install` or install through most package managers)

2. Make sure you have Docker installed. The pack cli needs a Docker daemon. You can set `DOCKER_HOST` and pack will pick this up if you use a remote Docker daemon.

3. Download the Paketo sample apps -> `git clone https://github.com/paketo-buildpacks/samples`

4. `cd samples/java/maven`

5. `pack build apps/maven -b paketo-buildpacks/java -b paketo-buildpacks/datadog -e BP_DATADOG_ENABLED=true`. The first two arguments are a requirement now, but won't be required after a 1.0 release is cut. The third argument toggles on/off the Datadog trace agent. If you set it to false or omit, false is the default, the build will fail. Again, after 1.0 is cut it won't fail, it'll just build an image w/out Datadog.

6. Unzip the attached archive, it has two files `conf.d/jmx.d/conf.yaml` and `docker-compose.yml`. The former configures the Datadog agent to pull metrics over JMX and the latter can be used to start the image we just built & the Datadog agent. It configures Docker such that they share the same network namespace, which allows the agent to talk to the JVM over JMX over localhost (so we don't have to expose JMX outside the container). These should be in the `samples/java/maven` directory, so `samples/java/maven/conf.d/...` and `samples/java/maven/docker-compose.yml`.

7. Edit docker-compose.yml and add your Datadog API key.

8. Run `docker compose up` from `samples/java/maven`. It should start two containers, maven-datadog-1 and maven-maven-1. The former is the Datadog agent and the latter is our App.

Keys to ensure things are working:

1. You should see this line, which confirms that the Datadog agent is able to connect over JMX.

maven-datadog-1  | 2022-03-10 18:27:26 GMT | JMX | INFO | Instance | Connected to JMX Server at jmx_instance

2. You should see this line which confirms that the Datadog agent was able to pull metrics over JMX.

maven-datadog-1  | 2022-03-10 18:27:26 GMT | JMX | INFO | Reporter | Instance jmx_instance is sending 27 metrics to the metrics reporter during collection #1

3. You should see these two lines which indicate the app is up and running and listening for traffic:

maven-maven-1    | 2022-03-10 18:27:23.402  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
maven-maven-1    | 2022-03-10 18:27:23.425  INFO 1 --- [           main] io.paketo.demo.DemoApplication           : Started DemoApplication in 3.644 seconds (JVM running for 5.706)

4. You should be able to `curl http://localhost:8080/actuator/health and it should respond with '{"status":"UP"}'. (If you have a remote docker daemon, you'll need to change localhost to the IP of your docker daemon.

5. Look in the Datadog dashboard. You should see metrics being reported.

6. Run `watch -n 1 curl -s http://$DOCKER_IP:8080/actuator/health` and let it run for a few minutes.

7. Refresh your Datadog dashboard and look at APM -> Traces. You should see traces for the requests being generated.

[datadog-bp-cfg.zip](https://github.com/paketo-buildpacks/datadog/files/8362778/datadog-bp-cfg.zip)

**Comment by mhubig** [comment]
Thanks for the detailed description! I got it to build now ...

**Comment by dmikusa-pivotal** [comment]
Awesome! I'll close this out.
