### ISSUE TITLE
Idea: Do not use version in dd-java-agent-<version>.jar

### ISSUE THREAD

**Issue by tjuchniewicz** [paketo-buildpacks/datadog#323]
My idea would be to skip version number in `dd-java-agent-<version>.jar` file used by this BP.

## Describe the Enhancement
This would allow to overwrite `BP_NATIVE_IMAGE_BUILD_ARGUMENTS` without knowing DD agent version. Currently to use `BP_NATIVE_IMAGE_BUILD_ARGUMENTS` we have to repeat DD agent parameter including version number which is not known before build:
```xml
 <BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
                    -O3
                    -J-Xmx14g
                    -J-javaagent:/layers/paketo-buildpacks_datadog/datadog-agent-java/dd-java-agent-${datadog-agent.version}.jar
</BP_NATIVE_IMAGE_BUILD_ARGUMENTS>
```
On every DD agent update we have to provide new value for `datadog-agent.version` in our CI.

## Motivation
This solution would be a workaround for native-image BP: https://github.com/paketo-buildpacks/native-image/issues/302

**Comment by dmikusa** [comment]
I don't think we can have the JAR file w/out a version number because we want the things on disk to be as clear as possible about what they are, but we could perhaps add a symlink where the symlink doesn't have a version number. That would give something consistent to point to.

**Comment by tjuchniewicz** [comment]
This would simplify our CI a lot. Can we expect this will be implemented?

**Comment by dmikusa** [comment]
It's a reasonable thing to implement so eventually, yes, I think it'll get implemented. Being realistic, it's OSS software so there are no timelines or guarantees we can provide. If this is time-critical for you, you can submit a PR and we'll do our best to review that and get it merged.

I suspect that the symlink would get added [here](https://github.com/paketo-buildpacks/datadog/blob/main/datadog/java_agent.go#L42) and then test coverage.

**Comment by tjuchniewicz** [comment]
@dmikusa Looks manageable for me. I will create PR next weeks. Thank you!
