### ISSUE TITLE
Image build failure with Docker 26

### ISSUE THREAD

**Issue by anishjayavant** [paketo-buildpacks/datadog#326]
## Expected Behavior
Container image should build with Docker version 26

## Current Behavior
The build fails with the error below
```bash
 > Pulled buildpack image 'gcr.io/paketo-buildpacks/datadog@sha256:04bb484caf0415f6cc02cbd1d5af26e7d388512b2fe78ffa839b01018366892f'
 > Executing lifecycle version v0.19.7
 > Using build cache volume 'pack-cache-d391cacd6169.build'

 > Running creator
    [creator]     ===> ANALYZING
    [creator]     Restoring data for SBOM from previous image
    [creator]     ===> DETECTING
    [creator]     ERROR: failed to initialize detector: open /cnb/buildpacks/paketo-buildpacks_datadog/5.17.0/buildpack.toml: no such file or directory
```

## Steps to Reproduce
**Spring boot image generation config**
```groovy
tasks.named("bootBuildImage") {
  imageName = "product-${project.name}"
  builder = "paketobuildpacks/builder-jammy-full"
  buildpacks = ["urn:cnb:builder:paketo-buildpacks/java", "gcr.io/paketo-buildpacks/datadog"]
  environment["BP_JVM_VERSION"] = "21"
  environment["BP_DATADOG_ENABLED"] = "true"
}
```

**Docker version**
```bash
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:49 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:49 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Spring Boot version:  `3.2.1`
Gradle version:  `8.5.1`

Other observations:
- The image build passes on Docker version 24
- The image build also passes if the datadog buildpack is removed from the configuration

A similar issue with latest Docker for a different build pack can be found [here](https://github.com/paketo-buildpacks/adoptium/issues/401).

## Motivations
To upgrade the Docker version used in all of our environments (developer environments, CI) to version 26 or higher.   Till this is resolved, our environments cannot be upgraded to the latest Docker version.  

If there is a workaround for the problem, would love to hear feedback.

**Comment by dmikusa** [comment]
Your Boot version is too old, you need to upgrade to 3.2.3+.

https://github.com/spring-projects/spring-boot/issues/39323#issuecomment-1930055126
